// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: lib/gobert/src/sentence_embedding.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentenceEmbeddingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Texts []string `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
}

func (x *SentenceEmbeddingRequest) Reset() {
	*x = SentenceEmbeddingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_gobert_src_sentence_embedding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentenceEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceEmbeddingRequest) ProtoMessage() {}

func (x *SentenceEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_gobert_src_sentence_embedding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*SentenceEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_lib_gobert_src_sentence_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *SentenceEmbeddingRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vectors []float32 `protobuf:"fixed32,1,rep,packed,name=vectors,proto3" json:"vectors,omitempty"`
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_gobert_src_sentence_embedding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_lib_gobert_src_sentence_embedding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_lib_gobert_src_sentence_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *Embedding) GetVectors() []float32 {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type SentenceEmbeddingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Texts []*Embedding `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
}

func (x *SentenceEmbeddingResponse) Reset() {
	*x = SentenceEmbeddingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_gobert_src_sentence_embedding_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentenceEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceEmbeddingResponse) ProtoMessage() {}

func (x *SentenceEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_gobert_src_sentence_embedding_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*SentenceEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_lib_gobert_src_sentence_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *SentenceEmbeddingResponse) GetTexts() []*Embedding {
	if x != nil {
		return x.Texts
	}
	return nil
}

var File_lib_gobert_src_sentence_embedding_proto protoreflect.FileDescriptor

var file_lib_gobert_src_sentence_embedding_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6c, 0x69, 0x62, 0x2f, 0x67, 0x6f, 0x62, 0x65, 0x72, 0x74, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x69, 0x2e, 0x73, 0x65,
	0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x22, 0x30, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x65, 0x78,
	0x74, 0x73, 0x22, 0x29, 0x0a, 0x09, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x1c, 0x0a, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02,
	0x42, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x53, 0x0a,
	0x19, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x74, 0x65,
	0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x69, 0x2e, 0x73,
	0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x74, 0x65, 0x78,
	0x74, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_gobert_src_sentence_embedding_proto_rawDescOnce sync.Once
	file_lib_gobert_src_sentence_embedding_proto_rawDescData = file_lib_gobert_src_sentence_embedding_proto_rawDesc
)

func file_lib_gobert_src_sentence_embedding_proto_rawDescGZIP() []byte {
	file_lib_gobert_src_sentence_embedding_proto_rawDescOnce.Do(func() {
		file_lib_gobert_src_sentence_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_gobert_src_sentence_embedding_proto_rawDescData)
	})
	return file_lib_gobert_src_sentence_embedding_proto_rawDescData
}

var file_lib_gobert_src_sentence_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lib_gobert_src_sentence_embedding_proto_goTypes = []interface{}{
	(*SentenceEmbeddingRequest)(nil),  // 0: ai.sentence_embedding.SentenceEmbeddingRequest
	(*Embedding)(nil),                 // 1: ai.sentence_embedding.Embedding
	(*SentenceEmbeddingResponse)(nil), // 2: ai.sentence_embedding.SentenceEmbeddingResponse
}
var file_lib_gobert_src_sentence_embedding_proto_depIdxs = []int32{
	1, // 0: ai.sentence_embedding.SentenceEmbeddingResponse.texts:type_name -> ai.sentence_embedding.Embedding
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lib_gobert_src_sentence_embedding_proto_init() }
func file_lib_gobert_src_sentence_embedding_proto_init() {
	if File_lib_gobert_src_sentence_embedding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_gobert_src_sentence_embedding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentenceEmbeddingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_gobert_src_sentence_embedding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Embedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_gobert_src_sentence_embedding_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentenceEmbeddingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_gobert_src_sentence_embedding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_gobert_src_sentence_embedding_proto_goTypes,
		DependencyIndexes: file_lib_gobert_src_sentence_embedding_proto_depIdxs,
		MessageInfos:      file_lib_gobert_src_sentence_embedding_proto_msgTypes,
	}.Build()
	File_lib_gobert_src_sentence_embedding_proto = out.File
	file_lib_gobert_src_sentence_embedding_proto_rawDesc = nil
	file_lib_gobert_src_sentence_embedding_proto_goTypes = nil
	file_lib_gobert_src_sentence_embedding_proto_depIdxs = nil
}
